#! /bin/sh -e

#edited in rules file
DIVERT_LIST="ldap sddm"

case "$1" in
    install|upgrade)

	if [ ! -d /usr/share/llx-pam-configs/diverted/ ]; then
		mkdir -p /usr/share/llx-pam-configs/diverted/ || true
	fi

	if [ ! -e /usr/share/llx-pam-configs/diverted/ldap.diverted  ]; then
		dpkg-divert --package llx-pam-configs --add --rename --divert /usr/share/llx-pam-configs/diverted/ldap.diverted /usr/share/pam-configs/ldap
	fi
	
	if [ ! -e /usr/share/llx-pam-configs/diverted/sddm.diverted  ]; then
                dpkg-divert --package llx-pam-configs --add --rename --divert /usr/share/llx-pam-configs/diverted/sddm.diverted /etc/pam.d/sddm
        fi


    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac





#DEBHELPER#

exit 0
